version: "3.7"
services:
    odoo:
        restart: unless-stopped
        env_file:
            - .docker/odoo.env
            - .docker/db-access.env
        environment:
            DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
            INITIAL_LANG: "$INITIAL_LANG"
            SMTP_SERVER: smtplocal
        depends_on:
            - db
            - smtp
        networks:
            default:
            inverseproxy_shared:
        labels:
            traefik.longpolling.frontend.rule:
                "Host:${DOMAIN_PROD};PathPrefix:/longpolling/"
            traefik.www.frontend.rule: "Host:${DOMAIN_PROD}"
            traefik.alt.frontend.rule: "Host:${DOMAIN_PROD_ALT}"
            traefik.alt.frontend.redirect.regex:
                "^(.*)://${DOMAIN_PROD_ALT}/(.*)$$"
            traefik.alt.frontend.redirect.replacement:
                "$$1://${DOMAIN_PROD}/$$2"

    db:
        env_file:
            - .docker/db-creation.env
        restart: unless-stopped

    smtp:
        env_file:
            - .docker/smtp.env
        networks:
            default:
                aliases:
                    - smtplocal
        restart: unless-stopped
        image: tvial/docker-mailserver:latest
        domainname: "$SMTP_REAL_MAILNAME"
        stop_grace_period: 1m
        volumes:
            - mailconfig:/tmp/docker-mailserver:z
            - maildata:/var/mail:z
            - maillogs:/var/log/mail:z
            - maillogssupervisord:/var/log/supervisor:z
            - mailstate:/var/mail-state:z
        cap_add:
            - SYS_PTRACE
        environment:
            DEFAULT_RELAY_HOST: "[$SMTP_REAL_RELAY_HOST]:$SMTP_REAL_RELAY_PORT"
            DMS_DEBUG: 0
            ENABLE_SRS: 1
            ONE_DIR: 1
            PERMIT_DOCKER: connected-networks
            POSTFIX_MESSAGE_SIZE_LIMIT: 52428800 # 50 MiB
            RELAY_HOST: "$SMTP_REAL_RELAY_HOST"
            RELAY_PORT: "$SMTP_REAL_RELAY_PORT"
            RELAY_USER: "$SMTP_REAL_RELAY_USER"
            SMTP_ONLY: 1
            SRS_DOMAINNAME: "$SMTP_REAL_NON_CANONICAL_DEFAULT"
            SRS_EXCLUDE_DOMAINS: "$SMTP_REAL_CANONICAL_DOMAINS"
            SRS_SENDER_CLASSES: envelope_sender,header_sender

    backup:
        image: tecnativa/duplicity:postgres-s3
        hostname: backup
        domainname: "$DOMAIN_PROD"
        init: true
        environment:
            DST: "s3://s3.amazonaws.com/$BACKUP_S3_BUCKET"
            EMAIL_FROM: "$BACKUP_EMAIL_FROM"
            EMAIL_TO: "$BACKUP_EMAIL_TO"
            PGDATABASE: *dbname
            PGUSER: *dbuser
            SMTP_HOST: smtplocal
        volumes:
            - backup_cache:/root:z
            - filestore:/mnt/backup/src/odoo:z
        env_file:
            - .docker/backup.env
            - .docker/db-access.env
        restart: unless-stopped
        depends_on:
            - db
            - smtp

networks:
    default:
        driver_opts:
            encrypted: 1

    inverseproxy_shared:
        external: true

volumes:
    backup_cache:
    filestore:
    db:
    mailconfig:
    maildata:
    maillogs:
    maillogssupervisord:
    mailstate:
